modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.${mod_id}]]

    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[mixins]]
config="mixins.blastwork.json"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

